apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
    - name: webserver
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/data"
          name: data-volume
  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: csi-pvc