apiVersion: v1
kind: ServiceAccount
metadata:
  name: dave
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: basic-user
subjects:
  - kind: ServiceAccount
    name: dave
    namespace: kube-system