## Ingress for load balancer
ingress:
  enabled: true
## Chartmuseum Ingress labels
##
#   labels:
#     dns: "route53"

## Chartmuseum Ingress annotations
##
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/tls-acme: "true"
#    cert-manager.io/issuer: "letsencrypt-staging"
    cert-manager.io/issuer: letsencrypt-production
    cert-manager.io/acme-challenge-type: http01

## Chartmuseum Ingress hostnames
## Must be provided if Ingress is enabled
##
  hosts:
    - name: chartmuseum.34.121.218.17.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.34.121.218.17.nip.io.secret
#    - name: chartmuseum.domain2.com
#      path: /
#
#      ## Set this to true in order to enable TLS on the ingress record
#      tls: true
#
#      ## If TLS is set to true, you must declare what secret will store the key/certificate for TLS
#      ## Secrets must be added manually to the namespace
#      tlsSecret: chartmuseum.domain2-tls
  certManager: true