# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: chartmuseum
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: guijseu674@gmail.com # ❗ Replace this with your email address
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            name: chartmuseum