backend:
  type: es
  es:
    host: elasticsearch-master
    time_key: "@timestamp" #https://github.com/fluent/fluent-bit/issues/628
tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule

image:
  fluent_bit:
    repository: fluent/fluent-bit
    tag: 1.8.12
  pullPolicy: Always

parsers:
  enabled: true
  regex:
    - name: log_parser
      regex: ^(?<logtimestamp>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
      timeKey: logtimestamp
      timeFormat: "%Y-%m-%dT%H:%M:%S.%L%z"

input:
  tail:
    parser: log_parser


  #filter:
  # If true, check to see if the log field content is a JSON string map, if so,
  # it append the map fields as part of the log structure.
  # https://github.com/fluent/fluent-bit/issues/628
  mergeJSONLog: true
  # If set, all unpacked keys from mergeJSONLog (Merge_Log) will be packed under
  # the key name specified on mergeLogKey (Merge_Log_Key)
  mergeLogKey: "app"